version: '3'
services:
  postgres:
    image: postgres:10.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: archive
      POSTGRES_PASSWORD: archive
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: