version: "3"
services:
  server:
    build:
      context: server/
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres
    ports:
      - ${PORT}:3000
    env_file:
      - .env
    volumes:
      - ./server:/server/app:z
      # Data mount dependencies
      - /server/node_modules
    restart: always

  postgres:
    image: postgres:10.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
