version: '3'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: 4x-archive
      POSTGRES_PASSWORD: 4x-archive
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: