version: "3.7"
services:
  postgres:
    image: postgres:10.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    restart: always

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "4000" # only docker-internally
    restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment: 
      VUE_APP_GRAPHQL_HTTP: ${VUE_APP_GRAPHQL_HTTP}
      VUE_APP_GRAPHQL_WS: ${VUE_APP_GRAPHQL_WS}
    depends_on:
      - server
    ports:
      - "80" # only docker-internally 

  proxy:
    image: nginx:1.16.0-alpine
    container_name: reverse_proxy
    depends_on: 
      - server
      - client
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/error.log:/etc/nginx/error_log.log
      - ./proxy/cache/:/etc/nginx/cache
      - ./proxy/cert/:/etc/cert/
      - ./proxy/ssl-key-pwd.lock/:/etc/keys/ssl-key-pwd
    ports:
      - 80:80
      - 443:443

volumes:
  postgres:
