apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: archive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: archive
            - name: DB_HOST
              value: postgres
            - name: DB_PASSWORD
              value: archive
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: archive
            - name: STORAGE_PATH
              value: archive-data
          image: server
          name: server
          ports:
            - containerPort: 4000
          resources: 
            limits:
                memory: "2Gi"
                cpu: "2"
          volumeMounts:
            - mountPath: /usr/src/app/archive-data
              name: archive-data
      restartPolicy: Always
      volumes:
        - name: archive-data
          persistentVolumeClaim:
            claimName: archive-data
status: {}
