apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: archive
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    app: server
status:
  loadBalancer: {}
