query Posts($after: String, $byContent: String) {
  posts(first: 40, after: $after, byContent: $byContent) {
    edges {
      node {
        id
        title
        creator {
          profilePicture
          username
        }
        items(first: 1) {
          totalCount
          edges {
            node {
              id
              __typename
              ... on VisualMediaItem {
                relativeHeight
                thumbnailPath
              }
              ... on AudioItem {
                ampThumbnail
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
      startCursor
    }
  }
}
