fragment PostData on Post {
  id
  title
  language
  updatedAt
  createdAt
  creator {
    name
    username
    profilePicture
  }
  keywords {
    name
    id
  }
  items {
    edges {
      node {
        __typename
        createdAt
        description
        position
        id
        creator {
          username
          profilePicture
        }
        ... on MediaItem {
          caption
          originalPath
          compressedPath
        }
        ... on VisualMediaItem {
          relativeHeight
          thumbnailPath
        }
      }
    }
  }
}

query Post($id: ID!) {
  node(id: $id) {
    ... on Post {
      ...PostData
    }
  }
}
