#import "./fragments.gql"

query me {
  me {
    name
    username
    profilePicture
    darkMode
    linkedTelegram
  }
}

query User($username: String!) {
  user(username: $username) {
    id
    username
    name
    profilePicture
    posts {
      totalCount
    }
  }
}

query Users($after: String, $search: String) {
  users(first: 50, after: $after, search: $search, sortByPostCount: true) {
    edges {
      node {
        id
        username
        name
        profilePicture
        postCount
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query UserWithPosts($username: String!, $after: String, $byContent: String) {
  user(username: $username) {
    id
    username
    name
    profilePicture
    postCount
  }
  posts(first: 24, after: $after, byContent: $byContent, byUsers: [$username]) {
    ...PostsConnection
  }
}
