query settings {
  me {
    name
    username
    profilePicture {
      profilePicture256
      profilePicture64
    }
    linkedTelegram
  }
  userSessions {
    createdAt
    firstIp
    id
    latestIp
    current
    userAgent
    updatedAt
  }
}
