query collections($after: String) {
    collections(first: 5, after: $after) {
        edges {
            node {
                id
                title
                creator {
                    username
                }
                posts(first: 3) {
                    totalCount
                    edges {
                        node {
                            color
                        }
                    }
                }
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
