query getNode($input: ID!) {
    node(id: $input) {
        id
        ... on Collection {
            title
            description
            createdAt
            posts(first: 3) {
                totalCount
                edges {
                    node {
                        thumbnailPath
                        color
                    }
                }
            }
            keywords {
                    id
                    name
            }
            creator {
                    name
                    username
                    profilePicture
            }
        }
    }
}
