mutation createCollection(
    $title: String!
    $description: String
    $keywords: [ID!]
) {
    createCollection(
        title: $title
        description: $description
        keywords: $keywords
    ) {
        id
    }
}
