mutation editCollection($id: ID!, $title: String, $keywords: [ID!], $description: String) {
    editCollection(id: $id, title: $title, keywords: $keywords, description: $description) {
        id
        title
        description
        keywords {
            id
        }
    }
}
