mutation editPost($id: ID!, $title: String, $keywords: [ID!], $language: Language, $caption: String, $description: String) {
    editPost(id: $id, title: $title, keywords: $keywords, language: $language, caption: $caption, description: $description) {
        id
        title
        language
        description
        caption
        keywords {
            id
        }
    }
}
