query getNode($input: ID!) {
    node(id: $input) {
        id
        ... on Post {
            title
            type
            compressedPath
            originalPath
            language
            createdAt
            caption
            keywords {
                    id
                    name
            }
            uploader {
                    name
                    username
                    profilePicture
            }
        }
    }
}
