query posts($after: String, $byUser: [ID!], $byKeyword: [ID!], $byType: [Format!], $byLanguage: Language, $byContent: String) {
    posts(first: 20, after: $after, byUser: $byUser, byKeyword: $byKeyword, byType: $byType, byLanguage: $byLanguage, byContent: $byContent) {
        edges {
            node {
                id
                title
                type
                relHeight
                color
                keywords {
                    name
                }
                thumbnailPath
                uploader {
                    name
                    username
                }
                caption
                updatedAt
                createdAt
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
