query {
    posts {
        id
        title
        type
        keywords {
            name
        }
        thumbnailPath
        uploader {
            name
            username
        }
        caption
        updatedAt
        createdAt
    }
}
