query tasks($after: String, $byTitle: String, $byUser: [ID!], $byStatus: [TaskStatus!]) {
    tasks(first: 10, after: $after, byUser: $byUser, byStatus: $byStatus, byTitle: $byTitle) {
        edges {
            node {
                id
                title
                status
                progress
                notes
                ext
                uploader {
                    name
                    username
                }
                createdPost {
                    id
                }
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
