mutation uploadPosts($title: String!, $caption: String, $language: Language!, $type: Format, $keywords: [ID!], $file: Upload!) {
    uploadPosts(title: $title, caption: $caption, language: $language, type: $type, keywords: $keywords, file: $file) {
        title
        uploader {
            username
        }
        status
    }
}
