query getUser($input: String!) {
    user(username: $input) {
        id
        name
        username
        profilePicture
        posts {
            totalCount
        }
        collections {
            totalCount
        }
    }
}
