fragment ItemData on Item {
  __typename
  createdAt
  description
  position
  id
  creator {
    username
    profilePicture
  }
  ... on MediaItem {
    caption
    originalPath
    compressedPath
  }
  ... on VisualMediaItem {
    relativeHeight
    thumbnailPath
  }
  ... on ProcessingItem {
    taskProgress
    taskStatus
    taskNotes
  }
}

fragment PostData on Post {
  id
  title
  language
  updatedAt
  createdAt
  creator {
    name
    username
    profilePicture
  }
  keywords {
    name
    id
  }
  items {
    edges {
      node {
        ...ItemData
      }
    }
  }
}

fragment PostsConnection on PostConnection {
  edges {
    node {
      id
      title
      creator {
        profilePicture
        username
      }
      items(first: 1) {
        totalCount
        edges {
          node {
            id
            __typename
            ... on VisualMediaItem {
              relativeHeight
              thumbnailPath
            }
            ... on AudioItem {
              ampThumbnail
            }
          }
        }
      }
    }
  }
  pageInfo {
    hasNextPage
    endCursor
    startCursor
  }
}
