fragment ItemData on Item {
  __typename
  createdAt
  description
  position
  id
  creator {
    username
    profilePicture {
      profilePicture256
      profilePicture64
    }
  }
  ... on VideoItem {
    file {
      __typename
      id
      processingStatus
      processingProgress
      processingNotes
      originalPath
      compressedPath
      thumbnailPath
      posterThumbnailPath
      relativeHeight
    }
    caption
    position
  }
  ... on ImageItem {
    file {
      __typename
      id
      processingStatus
      processingProgress
      processingNotes
      originalPath
      compressedPath
      thumbnailPath
      relativeHeight
    }
    caption
    position
  }
  ... on GifItem {
    file {
      __typename
      id
      processingStatus
      processingProgress
      processingNotes
      originalPath
      compressedPath
      compressedGifPath
      thumbnailPath
      relativeHeight
    }
    caption
    position
  }
  ... on AudioItem {
    file {
      __typename
      id
      processingStatus
      processingProgress
      processingNotes
      originalPath
      compressedPath
      waveform
    }
    caption
    position
  }
  ... on ProcessingItem {
    position
  }
}

fragment PostData on Post {
  id
  title
  language
  updatedAt
  createdAt
  creator {
    name
    username
    profilePicture {
      profilePicture256
      profilePicture64
    }
  }
  keywords {
    name
    id
  }
  items {
    nodes {
      ...ItemData
    }
  }
}

fragment PostsConnection on PostConnection {
  nodes {
    id
    title
    creator {
      profilePicture {
        profilePicture256
        profilePicture64
      }
      username
    }
    items(first: 1) {
      totalCount
      nodes {
        id
        __typename
        ... on VideoItem {
          file {
            __typename
            relativeHeight
            thumbnailPath
            posterThumbnailPath
          }
        }
        ... on ImageItem {
          file {
            __typename
            relativeHeight
            thumbnailPath
          }
        }
        ... on GifItem {
          file {
            __typename
            relativeHeight
            thumbnailPath
          }
        }
        ... on AudioItem {
          caption
          description
          file {
            __typename
            waveform
            waveformThumbnail
          }
        }
      }
    }
  }
  hasNextPage
  endCursor
  startCursor
}
