mutation changeName($newName: String!) {
  changeName(newName: $newName)
}

mutation changePassword($oldPassword: String!, $newPassword: String!) {
  changePassword(oldPassword: $oldPassword, newPassword: $newPassword)
}

mutation uploadPicture($file: Upload!) {
  uploadProfilePicture(file: $file)
}

mutation clearProfilePicture {
  clearProfilePicture
}
