mutation changeName($newName: String!) {
  changeName(newName: $newName)
}

mutation changePassword(
  $oldPassword: String!
  $newPassword: String!
  $code: String
) {
  changePassword(
    oldPassword: $oldPassword
    newPassword: $newPassword
    code: $code
  )
}

mutation uploadPicture($file: Upload!) {
  uploadProfilePicture(file: $file)
}

mutation clearProfilePicture {
  clearProfilePicture
}

query profilePictureStatus {
  me {
    profilePicture {
      processingStatus
      processingNotes
      profilePicture256
      profilePicture64
    }
  }
}
