#import "./fragments.gql"

query me {
  me {
    name
    username
    profilePicture {
      profilePicture256
      profilePicture64
    }
    linkedTelegram
  }
}

query User($username: String!) {
  user(username: $username) {
    id
    username
    name
    profilePicture {
      profilePicture256
      profilePicture64
    }
    posts {
      totalCount
    }
  }
}

query Users($after: String, $search: String) {
  users(first: 50, after: $after, search: $search, sortByPostCount: true) {
    nodes {
      id
      username
      name
      profilePicture {
        profilePicture256
        profilePicture64
      }
      postCount
    }
    hasNextPage
    endCursor
  }
}

query UserWithPosts($username: String!, $after: String, $byContent: String) {
  user(username: $username) {
    id
    username
    name
    profilePicture {
      profilePicture256
      profilePicture64
    }
    postCount
  }
  posts(first: 24, after: $after, byContent: $byContent, byUsers: [$username]) {
    ...PostsConnection
  }
}
