apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: server
  name: archive-data
  namespace: archive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
